In [1]:
import matplotlib.pyplot as plt 
import seaborn as sns
#plt.rcParams['figure.figsize']=8,4
import warnings
warnings.filterwarnings('ignore')
import pandas as pd

In [2]:
df=pd.read_csv('Crime_us.csv')

In [3]:
df.isnull().sum(axis=0)

ID                      828023
Case Number             828023
Date                    828023
Block                   828023
IUCR                    828023
Primary Type            828023
Description             828023
Location Description    828644
Arrest                  828023
Domestic                828023
Beat                    828023
District                828024
Ward                    828033
Community Area          828023
FBI Code                828023
X Coordinate            829532
Y Coordinate            829532
Year                    828023
Updated On              828023
Latitude                829532
Longitude               829532
Location                829532
dtype: int64

In [4]:
df

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,12789250.0,JF351068,01-01-2022 00:00,079XX S ST LAWRENCE AVE,810,THEFT,OVER $500,RESIDENCE,False,False,...,6.0,44.0,6,1181612.0,1852489.0,2022.0,11-12-2022 15:46,41.750462,-87.610059,"(41.75046233, -87.610058986)"
1,12783300.0,JF343908,01-01-2022 00:00,007XX N MICHIGAN AVE,580,STALKING,SIMPLE,STREET,False,False,...,42.0,8.0,08A,1177293.0,1905597.0,2022.0,11-12-2022 15:46,41.896294,-87.624280,"(41.896293625, -87.624279611)"
2,12814497.0,JF380963,01-01-2022 00:00,047XX W WABANSIA AVE,1563,SEX OFFENSE,CRIMINAL SEXUAL ABUSE,RESIDENCE - GARAGE,False,True,...,37.0,25.0,17,1144610.0,1910885.0,2022.0,11-12-2022 15:46,41.911483,-87.744185,"(41.911482929, -87.744185282)"
3,12822046.0,JF389504,01-01-2022 00:00,039XX N PINE GROVE AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,APARTMENT,False,False,...,46.0,6.0,11,1170694.0,1926410.0,2022.0,11-12-2022 15:46,41.953553,-87.647905,"(41.953552585, -87.647905229)"
4,12836994.0,JF403613,01-01-2022 00:00,042XX W WASHINGTON BLVD,1750,OFFENSE INVOLVING CHILDREN,CHILD ABUSE,RESIDENCE,False,True,...,28.0,26.0,08B,1148076.0,1900155.0,2022.0,11-12-2022 15:46,41.881973,-87.731729,"(41.881972634, -87.731728591)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048571,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048572,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048573,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048574,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.isna().sum(axis=0)

ID                      828023
Case Number             828023
Date                    828023
Block                   828023
IUCR                    828023
Primary Type            828023
Description             828023
Location Description    828644
Arrest                  828023
Domestic                828023
Beat                    828023
District                828024
Ward                    828033
Community Area          828023
FBI Code                828023
X Coordinate            829532
Y Coordinate            829532
Year                    828023
Updated On              828023
Latitude                829532
Longitude               829532
Location                829532
dtype: int64

In [6]:
df.dropna(axis=0)

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,12789250.0,JF351068,01-01-2022 00:00,079XX S ST LAWRENCE AVE,810,THEFT,OVER $500,RESIDENCE,False,False,...,6.0,44.0,6,1181612.0,1852489.0,2022.0,11-12-2022 15:46,41.750462,-87.610059,"(41.75046233, -87.610058986)"
1,12783300.0,JF343908,01-01-2022 00:00,007XX N MICHIGAN AVE,580,STALKING,SIMPLE,STREET,False,False,...,42.0,8.0,08A,1177293.0,1905597.0,2022.0,11-12-2022 15:46,41.896294,-87.624280,"(41.896293625, -87.624279611)"
2,12814497.0,JF380963,01-01-2022 00:00,047XX W WABANSIA AVE,1563,SEX OFFENSE,CRIMINAL SEXUAL ABUSE,RESIDENCE - GARAGE,False,True,...,37.0,25.0,17,1144610.0,1910885.0,2022.0,11-12-2022 15:46,41.911483,-87.744185,"(41.911482929, -87.744185282)"
3,12822046.0,JF389504,01-01-2022 00:00,039XX N PINE GROVE AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,APARTMENT,False,False,...,46.0,6.0,11,1170694.0,1926410.0,2022.0,11-12-2022 15:46,41.953553,-87.647905,"(41.953552585, -87.647905229)"
4,12836994.0,JF403613,01-01-2022 00:00,042XX W WASHINGTON BLVD,1750,OFFENSE INVOLVING CHILDREN,CHILD ABUSE,RESIDENCE,False,True,...,28.0,26.0,08B,1148076.0,1900155.0,2022.0,11-12-2022 15:46,41.881973,-87.731729,"(41.881972634, -87.731728591)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220547,12915874.0,JF502169,12-07-2022 23:50,040XX W 59TH ST,860,THEFT,RETAIL THEFT,TAVERN / LIQUOR STORE,False,False,...,23.0,65.0,6,1150629.0,1865174.0,2022.0,12/14/2022 03:49:33 PM,41.785931,-87.723266,"(41.785930664, -87.723266186)"
220548,12915875.0,JF502171,12-07-2022 23:51,044XX S DREXEL BLVD,496,BATTERY,AGGRAVATED DOMESTIC BATTERY - KNIFE / CUTTING ...,APARTMENT,False,True,...,4.0,39.0,04B,1182936.0,1875860.0,2022.0,12/14/2022 03:49:33 PM,41.814564,-87.604481,"(41.814563821, -87.604481355)"
220549,12917956.0,JF502185,12-07-2022 23:52,009XX N LAWNDALE AVE,486,BATTERY,DOMESTIC BATTERY SIMPLE,STREET,False,True,...,27.0,23.0,08B,1151546.0,1905984.0,2022.0,12/14/2022 03:49:33 PM,41.897901,-87.718833,"(41.897900553, -87.718833412)"
220550,12915844.0,JF502180,12-07-2022 23:58,013XX W 73RD ST,2091,NARCOTICS,FORFEIT PROPERTY,STREET,True,False,...,6.0,67.0,18,1168578.0,1856355.0,2022.0,12/14/2022 03:49:33 PM,41.761362,-87.657710,"(41.761361892, -87.657710237)"
220551,12915894.0,JF502215,12-07-2022 23:59,012XX S HARDING AVE,4310,OTHER OFFENSE,POSSESSION OF BURGLARY TOOLS,ABANDONED BUILDING,True,False,...,24.0,29.0,26,1150244.0,1894089.0,2022.0,12/14/2022 03:49:33 PM,41.865285,-87.723926,"(41.865284862, -87.723925799)"

In [7]:
df.isnull().sum(axis=0)

ID                      828023
Case Number             828023
Date                    828023
Block                   828023
IUCR                    828023
Primary Type            828023
Description             828023
Location Description    828644
Arrest                  828023
Domestic                828023
Beat                    828023
District                828024
Ward                    828033
Community Area          828023
FBI Code                828023
X Coordinate            829532
Y Coordinate            829532
Year                    828023
Updated On              828023
Latitude                829532
Longitude               829532
Location                829532
dtype: int64

In [2]:
d=pd.read_excel('crime.xlsx')

In [3]:
d.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,12789250,JF351068,2022-01-01,079XX S ST LAWRENCE AVE,810,THEFT,OVER $500,RESIDENCE,False,False,...,6.0,44,6,1181612.0,1852489.0,2022,2022-11-12 15:46:00,41.750462,-87.610059,"(41.75046233, -87.610058986)"
1,12783300,JF343908,2022-01-01,007XX N MICHIGAN AVE,580,STALKING,SIMPLE,STREET,False,False,...,42.0,8,08A,1177293.0,1905597.0,2022,2022-11-12 15:46:00,41.896294,-87.624280,"(41.896293625, -87.624279611)"
2,12814497,JF380963,2022-01-01,047XX W WABANSIA AVE,1563,SEX OFFENSE,CRIMINAL SEXUAL ABUSE,RESIDENCE - GARAGE,False,True,...,37.0,25,17,1144610.0,1910885.0,2022,2022-11-12 15:46:00,41.911483,-87.744185,"(41.911482929, -87.744185282)"
3,12822046,JF389504,2022-01-01,039XX N PINE GROVE AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,APARTMENT,False,False,...,46.0,6,11,1170694.0,1926410.0,2022,2022-11-12 15:46:00,41.953553,-87.647905,"(41.953552585, -87.647905229)"
4,12836994,JF403613,2022-01-01,042XX W WASHINGTON BLVD,1750,OFFENSE INVOLVING CHILDREN,CHILD ABUSE,RESIDENCE,False,True,...,28.0,26,08B,1148076.0,1900155.0,2022,2022-11-12 15:46:00,41.881973,-87.731729,"(41.881972634, -87.731728591)"

In [11]:
d.isnull().sum()

ID                         0
Case Number                0
Date                       0
Block                      0
IUCR                       0
Primary Type               0
Description                0
Location Description     621
Arrest                     0
Domestic                   0
Beat                       0
District                   1
Ward                      10
Community Area             0
FBI Code                   0
X Coordinate            1509
Y Coordinate            1509
Year                       0
Updated On                 0
Latitude                1509
Longitude               1509
Location                1509
dtype: int64

In [12]:
d.dropna(axis=0,inplace=True)

In [13]:
d.isnull().sum()

ID                      0
Case Number             0
Date                    0
Block                   0
IUCR                    0
Primary Type            0
Description             0
Location Description    0
Arrest                  0
Domestic                0
Beat                    0
District                0
Ward                    0
Community Area          0
FBI Code                0
X Coordinate            0
Y Coordinate            0
Year                    0
Updated On              0
Latitude                0
Longitude               0
Location                0
dtype: int64

In [14]:
d.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 218499 entries, 0 to 220551
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   ID                    218499 non-null  int64
 1   Case Number           218499 non-null  object
 2   Date                  218499 non-null  datetime64[ns]
 3   Block                 218499 non-null  object
 4   IUCR                  218499 non-null  object
 5   Primary Type          218499 non-null  object
 6   Description           218499 non-null  object
 7   Location Description  218499 non-null  object
 8   Arrest                218499 non-null  bool
 9   Domestic              218499 non-null  bool
 10  Beat                  218499 non-null  int64
 11  District              218499 non-null  float64
 12  Ward                  218499 non-null  float64
 13  Community Area        218499 non-null  int64
 14  FBI Code              218499 non-null  object
 15  X Coordinate          218499 non-null  float64
 16  Y Coordinate          218499 non-null  float64
 17  Year                  218499 non-null  int64
 18  Updated On            218499 non-null  datetime64[ns]
 19  Latitude              218499 non-null  float64
 20  Longitude             218499 non-null  float64
 21  Location              218499 non-null  object
dtypes: bool(2), datetime64[ns](2), float64(6), int64(4), object(8)
memory usage: 35.4+ MB

In [15]:
d.to_excel("cleaned_crime.xlsx",index=False)